# Generated by Django 4.2.8 on 2023-12-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
